#用户中心提供者
server:
  port: 8080
#dubbo配置
dubbo:
  application:
    id: dubbo-user-service
    #当前服务/应用的名字
    name: dubbo-user-service
  scan:
    # 包名根据自己的实际情况写
    base-packages: com.fengzi.dubbo.user
  protocol:
    port: 20771
    name: dubbo
  registry:
    #服务监控信息通过dubbo-admin查看
    address: zookeeper://127.0.0.1:2181
  provider:
    #过期时间
    timeout: 30000
    #服务分组
    group: dubbo
nacos:
  config:
    bootstrap:
      enable: true
    server-addr: 127.0.0.1:8848
    namespace: dev
    data-ids: redis.yaml
    type: yaml
    auto-refresh: true
    username: nacos
    password: nacos
