#商品中心服务端口
server:
  port: 8081
#dubbo配置
dubbo:
  application:
    id: dubbo-platform-provider
    #当前服务/应用的名字
    name: dubbo-platform-provider
  scan:
    # 包名根据自己的实际情况写
    base-packages: com.fengzi.dubbo.platform
  protocol:
    port: 20770
    name: dubbo
  registry:
    #address: zookeeper://8.136.176.62:2181
    address: nacos://127.0.0.1:8848
  consumer:
    #过期时间
    timeout: 30000
    #服务分组
    group: dubbo
    check: false
  provider:
    #过期时间
    timeout: 30000
    #服务分组
    group: dubbo
nacos:
  config:
    bootstrap:
      enable: true
    server-addr: 127.0.0.1:8848
    namespace: dev
    data-ids: redis.yaml
    type: yaml
    auto-refresh: true