#商品中心服务端口
server:
  port: 8081
#dubbo配置
dubbo:
  application:
    id: dubbo
    name: dubbo
  scan:
    # 包名根据自己的实际情况写
    base-packages: com.fengzi.dubbo.user
  protocol:
    port: 20770
    name: dubbo
  registry:
    #zookeeper注册中心地址
    address: zookeeper://127.0.0.1:2181