#用户中心服务端口
server:
  port: 8082
#dubbo配置
dubbo:
  application:
    id: dubbo-platform-consumer
    #当前服务/应用的名字
    name: dubbo-platform-consumer
  scan:
    # 包名根据自己的实际情况写
    base-packages: com.fengzi.dubbo.platform
  protocol:
    port: 20773
    name: dubbo
  registry:
    address: zookeeper://8.136.176.62:2181
  consumer:
    #过期时间
    timeout: 30000
    #服务分组
    group: dubbo
    check: false
  provider:
    #过期时间
    timeout: 30000
    #服务分组
    group: dubbo
