#用户中心服务端口
server:
  port: 8082
#dubbo配置
dubbo:
  application:
    id: dubbo-platform-consumer
    #当前服务/应用的名字
    name: dubbo-platform-consumer
  scan:
    # 包名根据自己的实际情况写
    base-packages: com.fengzi.dubbo.platform
  protocol:
    port: 20773
    name: dubbo
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    #过期时间
    timeout: 30000
    #服务分组
    group: dubbo
    check: false
  provider:
    #过期时间
    timeout: 30000
    #服务分组
    group: dubbo

spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200
#      username: elastic
#      password: 123456

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 特别注意：java 9以后需要将com.mysql.jdbc.Driver  改为  com.mysql.cj.jdbc.Driver即可
      # 否则报错：Loading class `com.mysql.jdbc.Driver'. This is deprecated.
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/marketing?charset=utf8mb4&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123
      #配置初始化大小/最小/最大[仅用于测试，生成环境需要修改哦]
      initial-size: 5
      min-idle: 5
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      #指定获取连接时连接校验的sql查询语句
      validation-query: SELECT 'x'
      #验证连接的有效性
      test-while-idle: true
      #获取连接时候验证，会影响性能（不建议true）
      test-on-borrow: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: config,wall,stat
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
nacos:
  config:
    bootstrap:
      enable: true
    server-addr: 127.0.0.1:8848
    namespace: dev
    data-ids: redis.yaml
    type: yaml
    auto-refresh: true
mybatis-plus:
  mapper-locations: classpath*:/com/fengzi/dubbo/*/mapper/xml/*.xml
